---
title: "D2SC ICMAs"
output: html_notebook
author: "Anya Prasad"
date: "2026-09-03"
---
# ICMA Sept 3 2026
```{r}
plot(cars)
```
The plot shows a positive relationship between speed and distance because as speed increases, so does distance.
```{r}
#| label: setup
#| include: false

library("tidyverse")
library("palmerpenguins")

```

# ICMA 9-10-2026

```{r}
ggplot(data=penguins, mapping = aes(x=flipper_length_mm,
                                    y= bill_length_mm)) + 
  geom_point()
```

```{r}
PlantGrowth
ggplot(data=PlantGrowth,
       mapping=aes(y=weight,x=group)) + 
  geom_point(alpha=0.5) +
  stat_summary(geom="pointrange",
               fun.dat="mean_se",
               color="purple")
```
Yes this is tidy data

#ICMA 9-15-2026
```{r}
PlantGrowth|>
ggplot(aes(y=weight,x=group)) +
geom_boxplot(width=0.2)
```

```{r}
flights |>
  arrange(desc(month))
```
```{r}
flights |> 
  filter(arr_delay > 120 & dep_delay ==0) |> arrange(desc(arr_delay))
```
```{r}
i<-flights |> 
  filter(arr_delay >120 & dep_delay ==0) |> 
  arrange(dep_delay)

j<-flights |> 
  arrange(dep_delay) |> 
  filter(arr_delay > 120 & dep_delay <= 0)
all(i == j)
```


```{r}
library(nycflights13)
flights <-nycflights13::flights
glimpse(flights)
```
```{r}
flights |> 
  # distance is miles, time is minutes
  # covert to miles/hour using *60
  mutate(speed=distance/air_time*60) |> 
  head()
```
``` {r}
flights |> 
  mutate(speed=distance/air_time*60,
         .after=distance) |> 
  glimpse()
```
```{r}
flights |> 
  mutate(speed=distance/air_time*60,
         .after=distance) |> 
  select(year,month,day,
         dep_time,air_time,distance,speed)
```
```{r}
flights |> 
  group_by(month,day) |> 
  count()
```
```{r}
flights_grounded<-flights |> 
  group_by(month)
flights_grounded |> 
  count()
flights_grouped |> 
  ungroup()
```
# ICMA sep 17 2026
```{r}
flights |> 
  group_by(month) |> 
  slice_max(dep_delay,n=2)
```
```{r}
flights |> 
group_by(month) |> 
  summarise(mean_delay=mean(arr_delay,na.rm=TRUE),
            sd_delay=sd(arr_delay,na.rm=TRUE),
            total_dep_delay=sum(dep_delay>0,na.rm=TRUE))

```
```{r}
flights |> 
group_by(month) |> 
  summarise(mean_delay=mean(arr_delay,na.rm=TRUE),
            sd_delay=sd(arr_delay,na.rm=TRUE),
            number_late=sum(arr_delay>0,na.rm=TRUE),
            total_number=n()) |> # pipe the result of...
  mutate(percentage=number_late/total_number) |> 
# want to add mutate? - which percentage of the total flight were late
# 
ggplot(aes(y=percentage,x=month))+
  geom_line()+
  scale_x_continuous(breaks=1:12)+
  ylim(0,0.55)
```
# ICMA Sept 22 2026
```{r}
library(nycflights13)
summary <- flights |>
  group_by (tailnum
  ) |> 
  summarize(
DELAY = mean(arr_delay, na.rm = TRUE), n=n())
```

```{r}
delay_summary <- flights |> 
  group_by(tailnum) |> 
  summarize(mean_delay = mean(arr_delay, na.rm = TRUE),
            n_flights = n())
```
```{r chnk-lbl,echo=TRUE}
# |> echo:TRUE
```
#ICMA Sept 28 2026
```{r}
library(tidyverse)
head(billboard)
```
```{r}
billboard |> 
  pivot_longer(cols = wk1:wk76,
               names_to = "week",
               values_to = "rank") |> 
  head(10)
# piping the billboard dataset to pivot_longer. then telling pivot_longer the cols i want to pivot are cols between cols names wk1 and wk76 inclusive. then im giving the argument names_to. naming the cols to be called 'week'. then i want to values to be called 'rank'. then head provides us the first 10 rows.
```
```{r}
billboard_long <- billboard |> 
  pivot_longer(cols = wk1:wk76,
               names_to = 'week',
               values_to = "rank")
#saving our billboard data thats pivoted in long format into variable called 'billboard_long'
```
```{r}
billboard |> 
  filter(track == "Baby Don't Cry (Keep...")
```
```{r}
billboard_long_dropna <- billboard |> 
  pivot_longer(cols = wk1:wk76,
               names_to = "week",
               values_to = "rank",
               values_drop_na = TRUE)
# after u run filtr its implicit missing
```
```{r}
billboard |> 
  pivot_longer(cols = wk1:wk76,
               names_to = "week",
               names_prefix = "wk",
               values_to = "rank",
               values_drop_na = TRUE)
#prefix is ignored when values and columns are set. our week column only has single digits
```
```{r}
billboard |> 
  pivot_longer(cols = starts_with("wk"),
               names_to = "week",
               names_prefix = "wk",
               values_to = "rank",
               values_drop_na = TRUE)
# long format data
```
```{r}
billboard |> 
  separate(col = date.entered,
           into = c("year", "month", "day"),
           sep = "-"
  ) |> 
  unite(col = date_entered,
        year:day,
        sep = "-",
        remove = TRUE
  )
# c(listing in quotation the names of the columns u want to seperate. this is called a vector with 3 elements).
# year:day - combine all columns with year and day inclusive
```
